### ISSUE TITLE
error during launch of Docker fika

### ISSUE THREAD

**Issue by cyberbobjr** [OnniSaarni/SPT-Fika-Docker-Guide#3]
Hello,
Thanks for this page, i encounter this error when i launch the fika docker :

`┌─────────────────────────────────────────┐
│ SPT-AKI 3.8.3                           │
│ https://discord.sp-tarkov.com           │
│                                         │
│ This work is free of charge             │
│ If you paid money, you were scammed     │
│ Commercial use is prohibited            │
└─────────────────────────────────────────┘
ModLoader: loading 2 server mods...
Mod: server version: 2.1.0 by: Fika loaded
Mod: SAIN version: 2.2.1 by: zSolarint loaded
The application had a critical error and failed to run
Exception produced: Error

Stacktrace:
Error: Cannot find module 'C:/snapshot/project/obj/models/enums/ConfigTypes'
Require stack:
- /opt/server/user/mods/zSolarint-SAIN-ServerMod/src/mod.js
- /snapshot/project/obj/loaders/PreAkiModLoader.js
- /snapshot/project/obj/controllers/GameController.js
- /snapshot/project/obj/callbacks/GameCallbacks.js
- /snapshot/project/obj/di/Container.js
- /snapshot/project/obj/Program.js
- /snapshot/project/obj/ide/ReleaseEntry.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/opt/server/user/mods/zSolarint-SAIN-ServerMod/src/mod.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (pkg/prelude/bootstrap.js:1894:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)`

do you have an idea please ?

**Comment by cyberbobjr** [comment]
Sorry my fault, i let some mods from my workstation to the server
